repos:
    - repo: https://github.com/myint/autoflake
      rev: "v2.0.1"
      hooks:
          - id: autoflake
            args:
                [
                    "--remove-unused-variables",
                    "--remove-all-unused-imports",
                    "--in-place",
                    ".",
                ]

    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id: black

    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: ["--profile", "black"]

    - repo: https://github.com/PyCQA/pylint
      rev: v2.16.2
      hooks:
          - id: pylint
            name: pylint
            entry: pylint
            language: system
            types: [python]
            args:
                [
                    "--exit-zero",
                    "--max-line-length=120",
                    "--ignore-imports=y",
                    "--ignore-comments=y",
                    "--ignore-docstrings=y",
                    "--disable=import-error",
                ]
