# Generated by Django 4.2 on 2023-04-04 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_types", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customtype",
            options={"ordering": ["name"]},
        ),
    ]
