# Generated by Django 4.2 on 2023-04-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonthlyBudget",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
