# Generated by Django 3.2.14 on 2023-04-10 23:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monthly_budgets", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monthlybudget",
            options={},
        ),
    ]
