# Generated by Django 4.2 on 2023-04-04 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monthly_budgets", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monthlybudget",
            options={"ordering": ["year", "month"]},
        ),
    ]
