# Generated by Django 4.2 on 2023-04-04 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monthly_budgets", "0003_alter_monthlybudget_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlybudget",
            name="budget",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
