# Generated by Django 4.2 on 2023-04-04 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monthly_budgets", "0004_alter_monthlybudget_budget"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monthlybudget",
            options={"ordering": ["-year", "-month"]},
        ),
    ]
