# Generated by Django 3.2.14 on 2023-04-05 16:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("custom_types", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ledger",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("memo", models.CharField(blank=True, max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="custom_types.customtype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ledgers",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SharedLedger",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "encoded_token",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ledger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ledgers.ledger"
                    ),
                ),
            ],
        ),
    ]
