# Generated by Django 4.2 on 2023-04-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledgers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedledger",
            name="encoded_token",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
