# Generated by Django 3.2.14 on 2023-04-10 23:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ledgers", "0003_remove_sharedledger_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ledger",
            options={"verbose_name_plural": "Ledgers"},
        ),
    ]
