# Generated by Django 3.2.14 on 2023-04-11 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ledgers", "0004_alter_ledger_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sharedledger",
            name="token",
        ),
    ]
